# Import external configurations
[general]
import = ["$XDG_CONFIG_HOME/.config/alacritty/catppuccin-macchiato.toml"]

[font]
normal = { family="JetBrainsMono Nerd Font", style="Regular" }
size = 17.0

[colors]
draw_bold_text_with_bright_colors = true

[window]
decorations = "Full"
dynamic_padding = true
decorations_theme_variant = "Dark"
option_as_alt = "None"
opacity = 1.0
