require("config.options")
require("config.keymaps")
require("config.plugins")
require("config.treesitter")
require("config.lualine")
require("config.nvimtree")
require("config.autopairs")
require("config.telescope")
require("config.blankline")
require("config.lsp")
require("config.cmp")

