#!/usr/bin/env zsh

# Default location for user configuration
export XDG_CONFIG_HOME="$HOME/.config"

##################################################
# Source Common Files
##################################################
source "$XDG_CONFIG_HOME/commonrc/envars"

