#!/usr/bin/env zsh

##################################################
# Source Common Files
##################################################
source "$HOME/.commonrc"
source "$HOME/.shell_functions"

# alt left/right in zsh
builtin bindkey "^[[1;3C" forward-word
builtin bindkey "^[[1;3D" backward-word
# ctrl a/e in zsh
builtin bindkey "^A" beginning-of-line
builtin bindkey "^E" end-of-line
# alt backspace in zsh
builtin bindkey "^[^H" backward-kill-word
builtin bindkey "^[^?" backward-kill-word

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/highlighters

###################################################
# Almost unlimited history
###################################################
HISTFILE="$HOME/.eternal_history"
HISTSIZE=500000
SAVEHIST="$HISTSIZE"
unsetopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS

###################################################
# zsh-completions settings
###################################################
if type brew &>/dev/null; then
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

# For Z for completion
. $(brew --prefix)/etc/profile.d/z.sh

# For Auto Suggestions
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=247'

# For Syntax Highlighting
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# FZF Completion
eval "$(fzf --zsh)"

# For asdf shims to be in the PATH
[[ -r "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh" ]] && source "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"
[[ -r "$HOME/.asdf/plugins/java/set-java-home.zsh" ]] && source "$HOME/.asdf/plugins/java/set-java-home.zsh"
[[ -r "$HOME/.asdf/plugins/golang/set-env.zsh" ]] && source "$HOME/.asdf/plugins/golang/set-env.zsh"
[[ -r "$HOME/.asdf/plugins/dotnet/set-dotnet-env.zsh" ]] && source "$HOME/.asdf/plugins/dotnet/set-dotnet-env.zsh"

# Starship terminal prompt
eval "$(starship init zsh)"
