#!/usr/bin/env zsh

###################################################
# Add common aliases and shell functions
###################################################
source "$XDG_CONFIG_HOME/commonrc/aliases"
source "$XDG_CONFIG_HOME/commonrc/shell_functions"

# Default WORDCHARS - Characters considered part of a word
# *?_-.[]~=/&;!#$%^(){}<>
export WORDCHARS=

# alt left/right in zsh
builtin bindkey "^[[1;3C" forward-word
builtin bindkey "^[[1;3D" backward-word
# ctrl a/e in zsh
builtin bindkey "^A" beginning-of-line
builtin bindkey "^E" end-of-line
# alt backspace in zsh
builtin bindkey "^[^H" backward-kill-word
builtin bindkey "^[^?" backward-kill-word

# Starship terminal prompt
eval "$(starship init zsh)"
