# ~/.config/starship.toml

palette = "catppuccin_latte"

# Inserts a blank line between shell prompts
add_newline = true

# Custom command timeout
command_timeout = 5000

# Change the default prompt format
format = """\
$os\
$battery\
$directory\
${custom.git_host}\
$git_branch\
$git_commit\
$git_status\
$git_state $fill\
$ansible\
$java\
$kotlin\
$dotnet\
$python\
$nodejs\
$rust\
$golang\
$ruby\
$hostname\
$jobs\
$shell\
$cmd_duration
$character"""

# Fill · in first row between left and right prompt
[fill]
symbol = "·"
style = "dimmed 244"

[battery]
format = " [$symbol$percentage]($style)"
full_symbol = "🔋"
charging_symbol = "󰂄"
discharging_symbol = "💀"
empty_symbol = "󰁺"

[git_state]
format = " [$state($progress_current$progress_total)]($style)"

# Change the default prompt characters
[character]
success_symbol = " [ ](bold green)"
error_symbol = " [ ](bold red)"
vimcmd_symbol = " [ ](bold green)"
vimcmd_replace_symbol = " [ ](bold purple)"
vimcmd_replace_one_symbol = " [ ](bold purple)"
vimcmd_visual_symbol = " [ ](bold yellow)"

# No need for env variables as starship provides a way to show your current distro
[os]
format =" [$symbol](bold white)"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰖳 "

# Shows the username
[username]
style_user = "blue bold"
style_root = "black bold"
format = " [$user]($style)"
disabled = true  # disable in powershell
show_always = false

[directory]
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false
style = "blue"
repo_root_style =  "blue bold"
read_only_style = "197"
read_only = " 🔒"
format = " [$path]($style)[$read_only]($read_only_style)"
repo_root_format = " [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = "\uF126"
format = " [$symbol $branch]($style)"
style = "green"

[git_commit]
tag_disabled = false

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "green"
untracked = " [?${count}](blue)"
ahead = " ⇡${count}"
diverged = " ⇡${ahead_count} ⇣${behind_count}"
behind = " ⇣${count}"
stashed = " 󰏗 ${count}"
modified = " [!${count}](yellow)"
staged = " [+${count}](yellow)"
renamed = " [»${count}](blue)"
deleted = " [✗${count}](red)"

# Configure the SSH prompt
[hostname]
ssh_only = true
format = "[ $ssh_symbol$hostname]($style)"

# Configure the background jobs
[jobs]
number_threshold = 1
symbol_threshold = 1
format = "[  $number]($style)"

[shell]
disabled = false
format = "[  $indicator]($style)"
style = "bold 244"
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
powershell_indicator = "pwsh"
cmd_indicator = "cmd"
tcsh_indicator = "tcsh"
elvish_indicator = "elsh"
xonsh_indicator = "xsh"
nu_indicator = "nush"
ion_indicator = "ionsh"

# Configure the package version
[package]
format = "[  $version]($style)"
style = "bold white"
disabled = true

# Configure the Node.js module
[nodejs]
format = "[ 󰎙 $version]($style)"
style = "bold green"

# Configure the golang module
[golang]
format = "[  $version]($style)"

# Configure the .NET module
[dotnet]
format = "[  $version]($style)"
style = "bold blue"
  
# Configure the Rust module
[rust]
format = "[  $version]($style)"
style = "bold red"

# Configure the Java module
[java]
format = "[  $version]($style)"
style = "bold purple"

[aws]
disabled = true

[terraform]
disabled = false
format = "[ 󱁢 $version]($style)"

[vagrant]
format = "[ V vagrant $version]($style)"

[docker_context]
format = "[  $context](blue bold)"

[helm]
format = "[  $version](bold purple)"

[python]
format = "[ 󰌠 $version ($virtualenv)]($style)"

[ruby]
format = "[  $version]($style)"

[kubernetes]
format = "[ 󱃾 $context](bold purple)"
disabled = true

[cmd_duration]
min_time = 10_000
style = "244"
format = "[  $duration]($style)"

[kotlin]
style = "bold blue"
format = "[ 󱈙 $version]($style)"

[custom.git_host]
command = """ source $XDG_CONFIG_HOME/commonrc/shell_functions && get_git_host_icon """
require_repo = true
when = "git rev-parse --is-inside-work-tree"
style = "green"
format = " [$output]($style)"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#2d2f3f"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#ffffff"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.tokyonight_storm]
base = "#414868"
bg = "#24283b"
blue = "#7aa2f7"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
bright_red = "#db4b4b"
crust = "#1d202f"
cyan = "#7dcfff"
fg = "#c0caf5"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
magenta = "#bb9af7"
magenta2 = "#ff007c"
orange = "#ff9e64"
purple = "#9d7cd8"
red = "#f7768e"
red1 = "#db4b4b"
teal = "#1abc9c"
text = "#a9b1d6"
yellow = "#e0af68"

[palettes.tokyonight_moon]
bg = "#222436"
bg_dark = "#1e2030"
bg_highlight = "#2f334d"
blue = "#82aaff"
blue0 = "#3e68d7"
blue1 = "#65bcff"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
comment = "#7a88cf"
cyan = "#86e1fc"
dark3 = "#545c7e"
dark5 = "#737aa2"
fg = "#c8d3f5"
fg_dark = "#828bb8"
fg_gutter = "#3b4261"
green = "#c3e88d"
green1 = "#4fd6be"
green2 = "#41a6b5"
magenta = "#c099ff"
magenta2 = "#ff007c"
orange = "#ff966c"
purple = "#fca7ea"
red = "#ff757f"
red1 = "#c53b53"
teal = "#4fd6be"
terminal_black = "#444a73"
yellow = "#ffc777"
