#!/usr/bin/env bash

##################################################
# Source Common Files
##################################################
source "$HOME/.commonrc"
source "$HOME/.shell_functions"

# alt left/right in bash
builtin bind '^[[1;3C:forward-word'
builtin bind '^[[1;3D:backward-word'
# ctrl a/e bash
builtin bind '^A:beginning-of-line'
builtin bind '^E:end-of-line'
# alt backspace in bash
builtin bind '^[^H:backward-kill-word'
builtin bind '^[^?:backward-kill-word'

################################################
# Case Insensitive completion
################################################
bind -s 'set completion-ignore-case on'

################################################
# Almost unlimited history
################################################
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE="$HOME/.eternal_history"
export HISTFILESIZE=
export HISTSIZE=
shopt -s histappend

# Bash completion
[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"

# FZF Completion
eval "$(fzf --bash)"

# For asdf shims to be in the PATH
[[ -r "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh" ]] && source "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"
[[ -r "$HOME/.asdf/plugins/java/set-java-home.bash" ]] && source "$HOME/.asdf/plugins/java/set-java-home.bash"
[[ -r "$HOME/.asdf/plugins/dotnet/set-dotnet-env.bash" ]] && source "$HOME/.asdf/plugins/dotnet/set-dotnet-env.bash"

# Starship terminal prompt
eval "$(starship init bash)"
