#!/usr/bin/env bash

# Default location for user configuration
export XDG_CONFIG_HOME="$HOME/.config"

if [ "$PS1" ]; then
    # only for interactive shell
    # alt left/right in bash
    builtin bind '^[[1;3C:forward-word'
    builtin bind '^[[1;3D:backward-word'
    # ctrl a/e bash
    builtin bind '^A:beginning-of-line'
    builtin bind '^E:end-of-line'
    # alt backspace in bash
    builtin bind '^[^H:backward-kill-word'
    builtin bind '^[^?:backward-kill-word'

    ################################################
    # Case Insensitive completion
    ################################################
    bind -s 'set completion-ignore-case on'

fi

##################################################
# Source Common Files
##################################################
source "$XDG_CONFIG_HOME/commonrc/envars"
source "$XDG_CONFIG_HOME/commonrc/aliases"
source "$XDG_CONFIG_HOME/commonrc/shell_functions"

# Starship terminal prompt
eval "$(starship init bash)"
