[font]
size = 16

[font.features]
"JetBrainsMono Nerd Font" = ["+zero", "+cv06", "+cv07", "+cv16", "+cv18", "+cv19", "+cv20"]

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[font.normal]]
family = "Symbols Nerd Font"
style = "Medium"

[[font.bold]]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[[font.bold]]
family = "Symbols Nerd Font"
style = "Bold"

[[font.italic]]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[[font.italic]]
family = "Symbols Nerd Font"
style = "Medium Italic"

[[font.bold_italic]]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[[font.bold_italic]]
family = "Symbols Nerd Font"
style = "Bold Italic"
